name: astrodyn-core-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - orekit=13.1
  - numpy
  - scipy
  - pandas
  - matplotlib
  - plotly
  - pyyaml
  - requests
  - fastparquet
  - h5py
  - cxx-compiler
  - cmake
  - ninja
  - scikit-build-core
  - pybind11
  - pip
  - pip:
      - spacetrack
